language: node_js
sudo: false
node_js:
  - "8"
install:
  - npm install
script:
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
deploy:
  - skip_cleanup: true
    provider: npm
    email: jenkins@xenit.eu
    api_key: $NPM_TOKEN
    on:
      tags: true
      condition: "$TRAVIS_TAG != v*.*.*-*" # Not for versions of the form x.x.x-prerelease
      repo: xenit-eu/finder-utils
  - skip_cleanup: true
    provider: npm
    email: jenkins@xenit.eu
    api_key: $NPM_TOKEN
    tag: next
    on:
      tags: true
      condition: "$TRAVIS_TAG == v*.*.*-*" # Only for versions of the form x.x.x-prerelease
      repo: xenit-eu/finder-utils
